### ISSUE TITLE
Give an alert for registration errors and co-requisite add errors

### ISSUE THREAD

**Issue by Sweetsbots** [cameronroudebush/Wright-State-Scheduler#16]
When users put in an invalid CRN or a CRN without a co-requisite course, no error messages are being presented or alerts to the user. The fix is to alert the user with a pop up notifying them of the error. This will allow them to fix the CRNs and re-schedule

**Comment by cameronroudebush** [comment]
Also create an alert that would tell the user to double check their crn's because our program will not/can not do that part for them before it attempts to schedule.
